[font]
size = 10

[font.bold]
family = "CaskaydiaCove Nerd Font"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"

[font.italic]
family = "CaskaydiaCove Nerd Font"

[font.normal]
family = "CaskaydiaCove Nerd Font"
